name: Update README ⭐
on:
  schedule:
    - cron: "51 */12 * * *"  # Every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2485485
          sessionCookie: ${{ secrets.AOC_SESSION }}
          starSymbol: 🦀
          year: 2023
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars